store start
Evgeny-TechnoNinja/learning_python_advanced_wave_2 pull request #6
Opened 2022-08-02 15:58 UTC by Evgeny-TechnoNinja

2022-08-03 16:50 UTC, shorodilov requested changes
Треба полагодити URL dispatcher, щоб уникати помилки на стороні сервера.
Необхідно зробити рефакторинг `product` вью.
Загалом - не погано.

2022-08-03 16:50 UTC, shorodilov commented on meteorites/shop/templates/shop/index.html
> +                            {% load static %}
Винось `{% load ... %}` на початок темплейта, це аналог `import ...`

2022-08-03 16:50 UTC, shorodilov commented on meteorites/shop/templates/products/products.html
> +{% endblock %}
Я не зрозумів, нащо ти виніс цей темплейт сюди. Якщо це по-приколу - то загалом так можна робити, але не треба. Лишай темплейти упорядкованими.

2022-08-03 16:50 UTC, shorodilov commented on meteorites/meteorites/urls.py
> +    path('product/<num>', product, name='product')
От тут не вистачає конвертера (`type converter`), це дуже весело закине тебе у 500-ку

2022-08-03 16:50 UTC, shorodilov commented on meteorites/shop/views.py
> +    product_id = request.path_info.split("/")[-1]
Нащо це тут? Он у тебе аргумент `num` пилом припадає

2022-08-04 16:51 UTC, Evgeny-TechnoNinja commented on meteorites/shop/templates/shop/index.html
> +                            {% load static %}
Полагодив

2022-08-04 18:19 UTC, Evgeny-TechnoNinja commented on meteorites/shop/templates/products/products.html
> +{% endblock %}
Полагодив

2022-08-04 18:23 UTC, Evgeny-TechnoNinja commented on meteorites/meteorites/urls.py
> +    path('product/<num>', product, name='product')
Полагодив

2022-08-04 18:28 UTC, Evgeny-TechnoNinja commented on meteorites/shop/views.py
> +    product_id = request.path_info.split("/")[-1]
Полагодив

2022-08-05 08:44 UTC, shorodilov approved these changes
Не дуже гарно використовувати "index.html" у якості імені шаблону.
Тай загалом, я б радив звикати до імен шаблонів виду "модель_тип": "product_list.html", "product_detail.html" etc.
Треба вилучити бд з репозиторія.

2022-08-05 08:44 UTC, shorodilov commented on meteorites/meteorites/settings.py
> +    'products.apps.ProductsConfig'
Не бачу великого сенсу виносити це до окремого застосунку

2022-08-05 08:44 UTC, shorodilov commented on meteorites/shop/views.py
> +
Не лишай шматки закоментованого коду - у тебе є для цього система контролю версій

2022-08-06 08:46 UTC, Evgeny-TechnoNinja commented on meteorites/meteorites/settings.py
> +    'products.apps.ProductsConfig'
Зрозумів

2022-08-06 08:47 UTC, Evgeny-TechnoNinja commented on meteorites/shop/views.py
> +
Виправив

2022-08-06 10:43 UTC, shorodilov approved these changes
LGTM

2022-08-06 10:43 UTC, shorodilov commented on meteorites/meteorites/settings.py
> -    'user.apps.UserConfig',
От юзера можно було не відключати. Тобі ж доведеться його повернути на завданні з аутентифікацією.
Основний посил був такий:
от є у тебе застосунок `user` - він відповідає за роботу з користувачами; є `shop` для опрацювання товарів.
А для чого `products`?

Зараз воно краще, але коли дивишся на темплейти - то трохи бентежно. Навіть якщо подивитись до `data.py` то стає зрозуміло, що існує контекст користувача і товару. Цим можно користуватись, щоб визначити, які застосунки будуть потрібні.

Хоча для цього проекта не є принциповою кільсть таких застосунків і якщо то зручно - можеш користвуватись одним.

2022-08-06 18:55 UTC, merged